//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "app", table_name = "sys_upload_files")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub file_id: i64,
    pub original_name: String,
    pub stored_path: String,
    #[sea_orm(unique)]
    pub file_url: String,
    pub file_size: Option<i64>,
    pub file_status: String,
    pub related_order_id: Option<i64>,
    pub uploader_name: Option<String>,
    pub upload_time: Option<DateTime>,
    pub remark: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
